// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.src.Infrastructure.Data;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240410055657_sqlite_migration_344")]
    partial class sqlite_migration_344
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("webapi.src.Domain.Models.ModuleModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("CreatorId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.SessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEvaluationReason")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Mark")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxScore")
                        .HasColumnType("REAL");

                    b.Property<string>("RecordingFilename")
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserModuleSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserModuleSessionId");

                    b.ToTable("SessionModels");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecoveryCodeValidBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("RestoreCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RestoreCodeValidBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenValidBefore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasPasswordResetRequest")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.UserModuleSessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleName");

                    b.HasIndex("UserId");

                    b.ToTable("UserModuleSessions");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.ModuleModel", b =>
                {
                    b.HasOne("webapi.src.Domain.Models.UserModel", "Creator")
                        .WithMany("CreatedModules")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.SessionModel", b =>
                {
                    b.HasOne("webapi.src.Domain.Models.UserModuleSessionModel", "UserModuleSession")
                        .WithMany("Sessions")
                        .HasForeignKey("UserModuleSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModuleSession");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.UserModuleSessionModel", b =>
                {
                    b.HasOne("webapi.src.Domain.Models.ModuleModel", "Module")
                        .WithMany("UserModuleSessions")
                        .HasForeignKey("ModuleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.src.Domain.Models.UserModel", "User")
                        .WithMany("UserModuleSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.ModuleModel", b =>
                {
                    b.Navigation("UserModuleSessions");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.UserModel", b =>
                {
                    b.Navigation("CreatedModules");

                    b.Navigation("UserModuleSessions");
                });

            modelBuilder.Entity("webapi.src.Domain.Models.UserModuleSessionModel", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
